/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'water' at '2/8/16 10:10 PM' with Gradle 2.11
 *
 * @author water, @date 2/8/16 10:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
